"""
FastAPI route handlers for the RAG API.

Thin layer: each handler validates the request, calls the appropriate
pipeline, and returns a serialized response. No business logic here.
"""

import logging
import os
import tempfile

from fastapi import APIRouter, HTTPException, UploadFile, File
from fastapi.responses import StreamingResponse

from app.api.schemas import (
    ChatRequest,
    ChatResponse,
    DocumentDeleteResponse,
    DocumentItem,
    DocumentListResponse,
    HealthResponse,
    IngestRequest,
    IngestResponse,
    SearchRequest,
    SearchResponse,
    SearchResultItem,
    SourceItem,
    UploadResponse,
)
from app.core.exceptions import (
    DocumentLoadError,
    EmbeddingError,
    IngestionError,
    RetrievalError,
    VectorStoreError,
)
from app.core.ports import DocumentRepositoryPort, EmbeddingPort, VectorStorePort
from app.pipeline.ingestion import IngestionPipeline
from app.pipeline.rag import RAGPipeline

logger = logging.getLogger(__name__)


def create_router(
    ingestion: IngestionPipeline,
    rag: RAGPipeline,
    vector_store: VectorStorePort,
    embedding: EmbeddingPort | None = None,
    doc_repo: DocumentRepositoryPort | None = None,
) -> APIRouter:
    """
    Factory function to create the API router with dependency injection.

    Args:
        ingestion: The ingestion pipeline instance.
        rag: The RAG pipeline instance.
        vector_store: The vector store instance.
        embedding: Optional embedding port for the search endpoint.
        doc_repo: Optional document repository for document management.

    Returns:
        A configured APIRouter with all endpoints.
    """
    router = APIRouter()

    @router.get("/health", response_model=HealthResponse)
    def health():
        """Health check endpoint."""
        try:
            count = vector_store.count()
        except Exception:
            count = -1

        return HealthResponse(
            status="ok" if count >= 0 else "degraded",
            vector_store_count=count,
        )

    @router.post("/ingest", response_model=IngestResponse)
    def ingest(request: IngestRequest):
        """
        Ingest a JSON file into the vector store.
        """
        try:
            chunks = ingestion.run(request.file_path)
            return IngestResponse(
                status="success",
                chunks_ingested=chunks,
            )
        except (FileNotFoundError, DocumentLoadError) as e:
            raise HTTPException(status_code=404, detail=str(e))
        except IngestionError as e:
            logger.exception("Ingestion failed")
            raise HTTPException(status_code=500, detail=str(e))
        except Exception as e:
            logger.exception("Unexpected ingestion error")
            raise HTTPException(status_code=500, detail=f"Ingestion failed: {e}")

    @router.post("/chat", response_model=ChatResponse)
    def chat(request: ChatRequest):
        """
        Ask a question and get an answer based on ingested documents.
        """
        if not request.question.strip():
            raise HTTPException(status_code=400, detail="Question cannot be empty")

        try:
            answer = rag.answer(request.question)
            return ChatResponse(
                answer=answer.text,
                sources=[
                    SourceItem(
                        content=s.chunk.text[:200],
                        metadata=s.chunk.metadata,
                        score=s.score,
                    )
                    for s in answer.sources
                ],
            )
        except RetrievalError as e:
            logger.exception("Chat failed")
            raise HTTPException(status_code=500, detail=str(e))
        except Exception as e:
            logger.exception("Unexpected chat error")
            raise HTTPException(status_code=500, detail=f"Chat failed: {e}")

    @router.post("/chat/stream")
    async def chat_stream(request: ChatRequest):
        """
        Ask a question and get a streaming answer based on ingested documents.

        Uses SSE (Server-Sent Events) to stream tokens progressively.
        The client receives tokens one by one as they are generated by the LLM,
        allowing for real-time display instead of waiting for the full response.
        """
        if not request.question.strip():
            raise HTTPException(status_code=400, detail="Question cannot be empty")

        return StreamingResponse(
            rag.answer_stream(request.question),
            media_type="text/plain",
        )

    @router.post("/search", response_model=SearchResponse)
    def search(request: SearchRequest):
        """
        Direct vector search — no LLM call.

        Embeds the query, searches ChromaDB, and returns raw matching
        chunks with their relevance scores and metadata.
        """
        if embedding is None:
            raise HTTPException(
                status_code=501,
                detail="Search endpoint is not available (embedding port not injected)",
            )

        if not request.query.strip():
            raise HTTPException(status_code=400, detail="Query cannot be empty")

        try:
            query_embedding = embedding.embed_query(request.query)
            results = vector_store.search(query_embedding, request.top_k)
        except EmbeddingError as e:
            logger.exception("Search embedding failed")
            raise HTTPException(status_code=500, detail=str(e))
        except Exception as e:
            logger.exception("Unexpected search error")
            raise HTTPException(status_code=500, detail=f"Search failed: {e}")

        return SearchResponse(
            query=request.query,
            total=len(results),
            results=[
                SearchResultItem(
                    content=r.chunk.text[:500],
                    metadata=r.chunk.metadata,
                    score=r.score,
                )
                for r in results
            ],
        )

    @router.post("/upload", response_model=UploadResponse)
    async def upload_file(file: UploadFile = File(...)):
        """
        Upload a file (JSON, MD, or TXT) and ingest it into the vector store.

        The file is saved to a temporary location, ingested, then deleted.
        """
        # validate extension
        ext = os.path.splitext(file.filename or "")[1].lower()
        if ext not in (".json", ".md", ".txt"):
            raise HTTPException(
                status_code=400,
                detail=f"Unsupported file type '{ext}'. Use .json, .md, or .txt",
            )

        # save to temp file
        tmp = tempfile.NamedTemporaryFile(
            suffix=ext, delete=False, mode="wb"
        )
        try:
            content = await file.read()
            tmp.write(content)
            tmp.close()

            chunks = ingestion.run(tmp.name)
            return UploadResponse(
                status="success",
                file_name=file.filename or "unknown",
                chunks_ingested=chunks,
                message=f"فایل با موفقیت بارگذاری شد. {chunks} قطعه استخراج شد.",
            )
        except (DocumentLoadError, IngestionError) as e:
            logger.exception("Upload ingestion failed")
            raise HTTPException(status_code=500, detail=str(e))
        except Exception as e:
            logger.exception("Unexpected upload error")
            raise HTTPException(status_code=500, detail=f"Upload failed: {e}")
        finally:
            if os.path.exists(tmp.name):
                os.unlink(tmp.name)

    # ------------------------------------------------------------------
    # Document Management Endpoints
    # ------------------------------------------------------------------

    @router.get("/documents", response_model=DocumentListResponse)
    def list_documents():
        """
        List all ingested documents with their metadata.
        """
        if doc_repo is None:
            raise HTTPException(
                status_code=501,
                detail="Document management is not available (doc_repo not injected)",
            )
        try:
            docs = doc_repo.list_all()
            return DocumentListResponse(
                total=len(docs),
                documents=[
                    DocumentItem(
                        id=d.id,
                        filename=d.filename,
                        source_path=d.source_path,
                        file_type=d.file_type,
                        chunk_count=d.chunk_count,
                        ingested_at=d.ingested_at,
                    )
                    for d in docs
                ],
            )
        except Exception as e:
            logger.exception("Failed to list documents")
            raise HTTPException(status_code=500, detail=str(e))

    @router.get("/documents/{doc_id}", response_model=DocumentItem)
    def get_document(doc_id: str):
        """
        Get metadata for a single ingested document.
        """
        if doc_repo is None:
            raise HTTPException(
                status_code=501,
                detail="Document management is not available (doc_repo not injected)",
            )
        try:
            doc = doc_repo.get(doc_id)
            if doc is None:
                raise HTTPException(status_code=404, detail="Document not found")
            return DocumentItem(
                id=doc.id,
                filename=doc.filename,
                source_path=doc.source_path,
                file_type=doc.file_type,
                chunk_count=doc.chunk_count,
                ingested_at=doc.ingested_at,
            )
        except HTTPException:
            raise
        except Exception as e:
            logger.exception("Failed to get document")
            raise HTTPException(status_code=500, detail=str(e))

    @router.delete("/documents/{doc_id}", response_model=DocumentDeleteResponse)
    def delete_document(doc_id: str):
        """
        Delete an ingested document and all its chunks from the vector store.
        """
        if doc_repo is None:
            raise HTTPException(
                status_code=501,
                detail="Document management is not available (doc_repo not injected)",
            )
        try:
            # Get document metadata first
            doc = doc_repo.get(doc_id)
            if doc is None:
                raise HTTPException(status_code=404, detail="Document not found")

            # Delete chunks from vector store by source_path metadata
            chunks_removed = vector_store.delete_by_metadata(
                "source", doc.source_path
            )

            # Delete document metadata
            doc_repo.delete(doc_id)

            return DocumentDeleteResponse(
                status="success",
                deleted=True,
                chunks_removed=chunks_removed,
            )
        except HTTPException:
            raise
        except VectorStoreError as e:
            logger.exception("Failed to delete document chunks")
            raise HTTPException(status_code=500, detail=str(e))
        except Exception as e:
            logger.exception("Failed to delete document")
            raise HTTPException(status_code=500, detail=str(e))

    return router
